Pkcs12 support
solacecommunity/solace-prometheus-exporter pull request #68
Opened 2024-03-05 16:51 UTC by GyroGearl00se

Our SCEP client provisions keystores in .p12 / pkcs12 format.
With this demand I've added the support for pkcs12 decoding and using it for ListenAndServeTLS (net/http).

To avoid a breaking change, "certType" will be set to PEM if the new parameter is not configured. This will ensure that the exporter will remain working for users with existing configuration and new release/build.
-> exporter/config.struct.go line 77-81

2024-03-06 08:44 UTC, GreenRover requested changes

2024-03-06 08:44 UTC, GreenRover commented on solace_prometheus_exporter.go
> +		var tlsCert tls.Certificate
Please move the whole TLS logic to an separate file and method. Try to avoid bloat up single files.

2024-03-06 08:45 UTC, GreenRover commented
@andreas-habel Can you please review, Because you introduced the whole SSL feature.

2024-03-06 10:52 UTC, GreenRover approved these changes

2024-03-11 14:16 UTC, GyroGearl00se commented
@GreenRover: After talking to andreas-habel, I'd ask you to wait please additional 1-2 days for his review.

2024-03-12 16:20 UTC, andreas-habel commented
👍  Looks good to me. 
The list of cipher suites introduced is a bit limited for now, but it's fairly easy to extend or even externalize the list later if necessary.

2024-03-12 16:22 UTC, merged

2024-03-12 16:23 UTC, GreenRover commented
https://github.com/solacecommunity/solace-prometheus-exporter/releases/tag/v1.6.0